version: '3.8'

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
#      - 443:443
    depends_on:
      - flask_app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
#      - ./certbot/www:/var/www/certbot/:ro
#      - ./certbot/conf/:/etc/nginx/ssl/:ro

#  certbot:
#    image: certbot/certbot:latest
#    volumes:
#      - ./certbot/www/:/var/www/certbot/:rw
#      - ./certbot/conf/:/etc/letsencrypt/:rw

  flask_app:
    build: ./flask_app
    container_name: flask_app
    ports:
      - 5000:5000
    command: >
      sh -c "python db.py &&
             python populate.py &&
             gunicorn -w 4 'app:app' -b 0.0.0.0:5000"
    volumes:
      - ./flask_app:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MERAKI_API_KEY=${MERAKI_API_KEY}
      - SHARED_SECRET=${SHARED_SECRET}
      - SERVICENOW_INSTANCE=${SERVICENOW_INSTANCE}
      - SERVICENOW_USERNAME=${SERVICENOW_USERNAME}
      - SERVICENOW_PASSWORD=${SERVICENOW_PASSWORD}
    depends_on:
      - redis

  worker:
    build: ./flask_app
    container_name: celery-worker
    command: celery -A app.celery worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./flask_app:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MERAKI_API_KEY=${MERAKI_API_KEY}
      - SHARED_SECRET=${SHARED_SECRET}
      - SERVICENOW_INSTANCE=${SERVICENOW_INSTANCE}
      - SERVICENOW_USERNAME=${SERVICENOW_USERNAME}
      - SERVICENOW_PASSWORD=${SERVICENOW_PASSWORD}
    depends_on:
      - flask_app
      - redis

  redis:
    container_name: redis
    image: redis:6-alpine